// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSwl4uKWzlC-c-OI2Wq4NY2ogGKiCqOuE',
    appId: '1:108309720514:web:29ab7ddec58e2c0f4aba5b',
    messagingSenderId: '108309720514',
    projectId: 'flutter-firebase-app-90c9a',
    authDomain: 'flutter-firebase-app-90c9a.firebaseapp.com',
    databaseURL: 'https://flutter-firebase-app-90c9a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-app-90c9a.appspot.com',
    measurementId: 'G-YCLNCQFJ7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgC_bd-p6bGBDeLFjq9lTxLJQOFn6_7dM',
    appId: '1:108309720514:android:948f6af6283dc8974aba5b',
    messagingSenderId: '108309720514',
    projectId: 'flutter-firebase-app-90c9a',
    databaseURL: 'https://flutter-firebase-app-90c9a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-app-90c9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Vg8T17vhwz_UKrvh3rbZ3RLdOpx5xkI',
    appId: '1:108309720514:ios:a0a75c61831ad9af4aba5b',
    messagingSenderId: '108309720514',
    projectId: 'flutter-firebase-app-90c9a',
    databaseURL: 'https://flutter-firebase-app-90c9a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-app-90c9a.appspot.com',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1Vg8T17vhwz_UKrvh3rbZ3RLdOpx5xkI',
    appId: '1:108309720514:ios:a0a75c61831ad9af4aba5b',
    messagingSenderId: '108309720514',
    projectId: 'flutter-firebase-app-90c9a',
    databaseURL: 'https://flutter-firebase-app-90c9a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-app-90c9a.appspot.com',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSwl4uKWzlC-c-OI2Wq4NY2ogGKiCqOuE',
    appId: '1:108309720514:web:931077b35a18c2854aba5b',
    messagingSenderId: '108309720514',
    projectId: 'flutter-firebase-app-90c9a',
    authDomain: 'flutter-firebase-app-90c9a.firebaseapp.com',
    databaseURL: 'https://flutter-firebase-app-90c9a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-app-90c9a.appspot.com',
    measurementId: 'G-7G39QTQH42',
  );
}
